version: '3.4'
services:
  database:
    container_name: db
    image: mariadb
    ports:
      - '3306:3306'    
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=my-secret-pW7770
    volumes:
      - ./data:/var/lib/mysql   
  phpmyadmin:
    container_name: php_admin
    image: phpmyadmin
    ports:
      - '8081:80'       
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - database
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:      
      - db_server=${db_server}
      - db_user=${db_user}
      - db_password=${db_password}
      - db_name=${db_name}
      - server_port=${server_port}
    restart: always
    depends_on:
      - database
    ports: 
      - 8080:8080