version: '3.4'
services:

  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 4000 --watch  db.json
    ports:
      - "3000:4000"
    volumes:
      - ./data:/data
    restart: always