version: '3.4'

services:
  server:
    image: server
    build:
      context: demo5_server_client_mariadb/backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
